In [1]:
import sys

import numpy as np

sys.path.insert(0, '..')
import os
from process_bigraph import pp, pf
from biosimulator_processes.data_model import *
import numpy as np 
from pydantic import field_validator, Field
from biosimulator_processes.biosimulator_builder import BiosimulatorBuilder

CobraProcess registered successfully.
CopasiProcess registered successfully.
SmoldynProcess registered successfully.
TelluriumProcess registered successfully.


Choose an entrypoint to a non-spatial, COPASI/Tellurium-like simulation process and perform an n-iteration parameter scan of a selected parameter.

In [72]:
x = np.arange(0, 10, 0.5)

In [3]:
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [47]:
class ParameterScanRange(BaseModel):
    num_iter: int 
    interval: int
    param_name: str 
    param_range: np.ndarray = Field(default=None) 
            
    def perturb(self):
        return np.linspace(
            start=0.0, 
            stop=self.num_iter, 
            num=self.interval)
        

In [51]:
scan = ParameterScanRange(
    num_iter=100,
    interval=100,
    param_name='ADP'
    
)

In [52]:
_range = scan.perturb()

In [54]:
_range.shape, _range

((100,),
 array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
          4.04040404,   5.05050505,   6.06060606,   7.07070707,
          8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
         12.12121212,  13.13131313,  14.14141414,  15.15151515,
         16.16161616,  17.17171717,  18.18181818,  19.19191919,
         20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
         24.24242424,  25.25252525,  26.26262626,  27.27272727,
         28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
         32.32323232,  33.33333333,  34.34343434,  35.35353535,
         36.36363636,  37.37373737,  38.38383838,  39.39393939,
         40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
         44.44444444,  45.45454545,  46.46464646,  47.47474747,
         48.48484848,  49.49494949,  50.50505051,  51.51515152,
         52.52525253,  53.53535354,  54.54545455,  55.55555556,
         56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
         60.60606061,  61.61616

In [34]:
y = np.linspace(0, 100, 100)

In [35]:
len(y), y

(100,
 array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
          4.04040404,   5.05050505,   6.06060606,   7.07070707,
          8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
         12.12121212,  13.13131313,  14.14141414,  15.15151515,
         16.16161616,  17.17171717,  18.18181818,  19.19191919,
         20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
         24.24242424,  25.25252525,  26.26262626,  27.27272727,
         28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
         32.32323232,  33.33333333,  34.34343434,  35.35353535,
         36.36363636,  37.37373737,  38.38383838,  39.39393939,
         40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
         44.44444444,  45.45454545,  46.46464646,  47.47474747,
         48.48484848,  49.49494949,  50.50505051,  51.51515152,
         52.52525253,  53.53535354,  54.54545455,  55.55555556,
         56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
         60.60606061,  61.61616162

In [25]:
len(_range)

417

In [27]:
y.shape

(100,)

In [28]:
y[:10]

array([0.        , 1.01010101, 2.02020202, 3.03030303, 4.04040404,
       5.05050505, 6.06060606, 7.07070707, 8.08080808, 9.09090909])

In [67]:
y = np.arange(start=0, stop=100, step=2.0)

In [68]:
y.shape, y

((50,),
 array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
        26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.,
        52., 54., 56., 58., 60., 62., 64., 66., 68., 70., 72., 74., 76.,
        78., 80., 82., 84., 86., 88., 90., 92., 94., 96., 98.]))

In [64]:
# ADD PARAMETER SCAN AS A STEP IMPLEMENTATION

In [74]:
def perturbed_parameter_range(num_iter: int, degree: float):
    _range = []
    for n in range(num_iter):
        if n > 0:
            n = n * degree 
        _range.append(n)
    return _range 

In [78]:
r = perturbed_parameter_range(100, 0.0023)

In [79]:
r

[0,
 0.0023,
 0.0046,
 0.0069,
 0.0092,
 0.0115,
 0.0138,
 0.0161,
 0.0184,
 0.0207,
 0.023,
 0.0253,
 0.0276,
 0.0299,
 0.0322,
 0.0345,
 0.0368,
 0.039099999999999996,
 0.0414,
 0.0437,
 0.046,
 0.048299999999999996,
 0.0506,
 0.0529,
 0.0552,
 0.057499999999999996,
 0.0598,
 0.0621,
 0.0644,
 0.0667,
 0.069,
 0.0713,
 0.0736,
 0.0759,
 0.07819999999999999,
 0.0805,
 0.0828,
 0.0851,
 0.0874,
 0.0897,
 0.092,
 0.0943,
 0.09659999999999999,
 0.0989,
 0.1012,
 0.1035,
 0.1058,
 0.1081,
 0.1104,
 0.1127,
 0.11499999999999999,
 0.1173,
 0.1196,
 0.1219,
 0.1242,
 0.1265,
 0.1288,
 0.1311,
 0.1334,
 0.1357,
 0.138,
 0.1403,
 0.1426,
 0.1449,
 0.1472,
 0.1495,
 0.1518,
 0.1541,
 0.15639999999999998,
 0.1587,
 0.161,
 0.1633,
 0.1656,
 0.1679,
 0.1702,
 0.1725,
 0.1748,
 0.1771,
 0.1794,
 0.1817,
 0.184,
 0.1863,
 0.1886,
 0.1909,
 0.19319999999999998,
 0.1955,
 0.1978,
 0.2001,
 0.2024,
 0.2047,
 0.207,
 0.20929999999999999,
 0.2116,
 0.2139,
 0.2162,
 0.2185,
 0.2208,
 0.2231,
 0.2254,
 0

In [80]:
len(r)

100